#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : samtools
Version  : 1.10
Release  : 2
URL      : https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2
Source0  : https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2
Summary  : C library for high-throughput sequencing data formats
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT
Requires: samtools-bin = %{version}-%{release}
Requires: samtools-license = %{version}-%{release}
Requires: samtools-man = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : curl-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : xz-dev

%description
Samtools implements various utilities for post-processing alignments in the
SAM, BAM, and CRAM formats, including indexing, variant calling (in conjunction
with bcftools), and a simple alignment viewer.

%package bin
Summary: bin components for the samtools package.
Group: Binaries
Requires: samtools-license = %{version}-%{release}

%description bin
bin components for the samtools package.


%package license
Summary: license components for the samtools package.
Group: Default

%description license
license components for the samtools package.


%package man
Summary: man components for the samtools package.
Group: Default

%description man
man components for the samtools package.


%prep
%setup -q -n samtools-1.10
cd %{_builddir}/samtools-1.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1576620956
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1576620956
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/samtools
cp %{_builddir}/samtools-1.10/LICENSE %{buildroot}/usr/share/package-licenses/samtools/ee07ac3b080ba8a04c9180209555f61088165191
cp %{_builddir}/samtools-1.10/htslib-1.10/LICENSE %{buildroot}/usr/share/package-licenses/samtools/6a9fda1ee5bdca4863a27d95d7b94669a27259fa
cp %{_builddir}/samtools-1.10/lz4/LICENSE %{buildroot}/usr/share/package-licenses/samtools/10bf56381baaf07f0647b93a810eb4e7e9545e8d
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ace2sam
/usr/bin/blast2sam.pl
/usr/bin/bowtie2sam.pl
/usr/bin/export2sam.pl
/usr/bin/interpolate_sam.pl
/usr/bin/maq2sam-long
/usr/bin/maq2sam-short
/usr/bin/md5fa
/usr/bin/md5sum-lite
/usr/bin/novo2sam.pl
/usr/bin/plot-bamstats
/usr/bin/psl2sam.pl
/usr/bin/sam2vcf.pl
/usr/bin/samtools
/usr/bin/samtools.pl
/usr/bin/seq_cache_populate.pl
/usr/bin/soap2sam.pl
/usr/bin/wgsim
/usr/bin/wgsim_eval.pl
/usr/bin/zoom2sam.pl

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/samtools/10bf56381baaf07f0647b93a810eb4e7e9545e8d
/usr/share/package-licenses/samtools/6a9fda1ee5bdca4863a27d95d7b94669a27259fa
/usr/share/package-licenses/samtools/ee07ac3b080ba8a04c9180209555f61088165191

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/samtools-addreplacerg.1
/usr/share/man/man1/samtools-bedcov.1
/usr/share/man/man1/samtools-calmd.1
/usr/share/man/man1/samtools-cat.1
/usr/share/man/man1/samtools-collate.1
/usr/share/man/man1/samtools-depad.1
/usr/share/man/man1/samtools-depth.1
/usr/share/man/man1/samtools-dict.1
/usr/share/man/man1/samtools-faidx.1
/usr/share/man/man1/samtools-fasta.1
/usr/share/man/man1/samtools-fastq.1
/usr/share/man/man1/samtools-fixmate.1
/usr/share/man/man1/samtools-flags.1
/usr/share/man/man1/samtools-flagstat.1
/usr/share/man/man1/samtools-fqidx.1
/usr/share/man/man1/samtools-idxstats.1
/usr/share/man/man1/samtools-index.1
/usr/share/man/man1/samtools-markdup.1
/usr/share/man/man1/samtools-merge.1
/usr/share/man/man1/samtools-mpileup.1
/usr/share/man/man1/samtools-phase.1
/usr/share/man/man1/samtools-quickcheck.1
/usr/share/man/man1/samtools-reheader.1
/usr/share/man/man1/samtools-rmdup.1
/usr/share/man/man1/samtools-sort.1
/usr/share/man/man1/samtools-split.1
/usr/share/man/man1/samtools-stats.1
/usr/share/man/man1/samtools-targetcut.1
/usr/share/man/man1/samtools-tview.1
/usr/share/man/man1/samtools-view.1
/usr/share/man/man1/samtools.1
/usr/share/man/man1/wgsim.1
