#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v10
# autospec commit: 5905be9
#
Name     : samtools
Version  : 1.20
Release  : 9
URL      : https://github.com/samtools/samtools/releases/download/1.20/samtools-1.20.tar.bz2
Source0  : https://github.com/samtools/samtools/releases/download/1.20/samtools-1.20.tar.bz2
Summary  : C library for high-throughput sequencing data formats
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT
Requires: samtools-bin = %{version}-%{release}
Requires: samtools-license = %{version}-%{release}
Requires: samtools-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : bzip2-dev
BuildRequires : curl-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Samtools implements various utilities for post-processing alignments in the
SAM, BAM, and CRAM formats, including indexing, variant calling (in conjunction
with bcftools), and a simple alignment viewer.

%package bin
Summary: bin components for the samtools package.
Group: Binaries
Requires: samtools-license = %{version}-%{release}

%description bin
bin components for the samtools package.


%package license
Summary: license components for the samtools package.
Group: Default

%description license
license components for the samtools package.


%package man
Summary: man components for the samtools package.
Group: Default

%description man
man components for the samtools package.


%prep
%setup -q -n samtools-1.20
cd %{_builddir}/samtools-1.20
pushd ..
cp -a samtools-1.20 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713205795
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --disable-lzma
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --disable-lzma
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1713205795
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/samtools
cp %{_builddir}/samtools-%{version}/htslib-%{version}/htscodecs/LICENSE.md %{buildroot}/usr/share/package-licenses/samtools/6c4957c5b4497597ff61a6a6cef7b08eacbc7731 || :
cp %{_builddir}/samtools-%{version}/lz4/LICENSE %{buildroot}/usr/share/package-licenses/samtools/10bf56381baaf07f0647b93a810eb4e7e9545e8d || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/ace2sam
/V3/usr/bin/maq2sam-long
/V3/usr/bin/maq2sam-short
/V3/usr/bin/md5fa
/V3/usr/bin/md5sum-lite
/V3/usr/bin/samtools
/V3/usr/bin/wgsim
/usr/bin/ace2sam
/usr/bin/blast2sam.pl
/usr/bin/bowtie2sam.pl
/usr/bin/export2sam.pl
/usr/bin/fasta-sanitize.pl
/usr/bin/interpolate_sam.pl
/usr/bin/maq2sam-long
/usr/bin/maq2sam-short
/usr/bin/md5fa
/usr/bin/md5sum-lite
/usr/bin/novo2sam.pl
/usr/bin/plot-ampliconstats
/usr/bin/plot-bamstats
/usr/bin/psl2sam.pl
/usr/bin/sam2vcf.pl
/usr/bin/samtools
/usr/bin/samtools.pl
/usr/bin/seq_cache_populate.pl
/usr/bin/soap2sam.pl
/usr/bin/wgsim
/usr/bin/wgsim_eval.pl
/usr/bin/zoom2sam.pl

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/samtools/10bf56381baaf07f0647b93a810eb4e7e9545e8d
/usr/share/package-licenses/samtools/6c4957c5b4497597ff61a6a6cef7b08eacbc7731

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/samtools-addreplacerg.1
/usr/share/man/man1/samtools-ampliconclip.1
/usr/share/man/man1/samtools-ampliconstats.1
/usr/share/man/man1/samtools-bedcov.1
/usr/share/man/man1/samtools-calmd.1
/usr/share/man/man1/samtools-cat.1
/usr/share/man/man1/samtools-collate.1
/usr/share/man/man1/samtools-consensus.1
/usr/share/man/man1/samtools-coverage.1
/usr/share/man/man1/samtools-cram-size.1
/usr/share/man/man1/samtools-depad.1
/usr/share/man/man1/samtools-depth.1
/usr/share/man/man1/samtools-dict.1
/usr/share/man/man1/samtools-faidx.1
/usr/share/man/man1/samtools-fasta.1
/usr/share/man/man1/samtools-fastq.1
/usr/share/man/man1/samtools-fixmate.1
/usr/share/man/man1/samtools-flags.1
/usr/share/man/man1/samtools-flagstat.1
/usr/share/man/man1/samtools-fqidx.1
/usr/share/man/man1/samtools-head.1
/usr/share/man/man1/samtools-idxstats.1
/usr/share/man/man1/samtools-import.1
/usr/share/man/man1/samtools-index.1
/usr/share/man/man1/samtools-markdup.1
/usr/share/man/man1/samtools-merge.1
/usr/share/man/man1/samtools-mpileup.1
/usr/share/man/man1/samtools-phase.1
/usr/share/man/man1/samtools-quickcheck.1
/usr/share/man/man1/samtools-reference.1
/usr/share/man/man1/samtools-reheader.1
/usr/share/man/man1/samtools-reset.1
/usr/share/man/man1/samtools-rmdup.1
/usr/share/man/man1/samtools-samples.1
/usr/share/man/man1/samtools-sort.1
/usr/share/man/man1/samtools-split.1
/usr/share/man/man1/samtools-stats.1
/usr/share/man/man1/samtools-targetcut.1
/usr/share/man/man1/samtools-tview.1
/usr/share/man/man1/samtools-view.1
/usr/share/man/man1/samtools.1
/usr/share/man/man1/wgsim.1
