#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : samtools
Version  : 1.9
Release  : 1
URL      : https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2
Source0  : https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2
Summary  : C library for high-throughput sequencing data formats
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT MIT-feh
Requires: samtools-bin = %{version}-%{release}
Requires: samtools-license = %{version}-%{release}
Requires: samtools-man = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : curl-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : xz-dev

%description
Samtools implements various utilities for post-processing alignments in the
SAM, BAM, and CRAM formats, including indexing, variant calling (in conjunction
with bcftools), and a simple alignment viewer.

%package bin
Summary: bin components for the samtools package.
Group: Binaries
Requires: samtools-license = %{version}-%{release}

%description bin
bin components for the samtools package.


%package license
Summary: license components for the samtools package.
Group: Default

%description license
license components for the samtools package.


%package man
Summary: man components for the samtools package.
Group: Default

%description man
man components for the samtools package.


%prep
%setup -q -n samtools-1.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570824471
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1570824471
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/samtools
cp LICENSE %{buildroot}/usr/share/package-licenses/samtools/LICENSE
cp htslib-1.9/LICENSE %{buildroot}/usr/share/package-licenses/samtools/htslib-1.9_LICENSE
cp lz4/LICENSE %{buildroot}/usr/share/package-licenses/samtools/lz4_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ace2sam
/usr/bin/blast2sam.pl
/usr/bin/bowtie2sam.pl
/usr/bin/export2sam.pl
/usr/bin/interpolate_sam.pl
/usr/bin/maq2sam-long
/usr/bin/maq2sam-short
/usr/bin/md5fa
/usr/bin/md5sum-lite
/usr/bin/novo2sam.pl
/usr/bin/plot-bamstats
/usr/bin/psl2sam.pl
/usr/bin/sam2vcf.pl
/usr/bin/samtools
/usr/bin/samtools.pl
/usr/bin/seq_cache_populate.pl
/usr/bin/soap2sam.pl
/usr/bin/varfilter.py
/usr/bin/wgsim
/usr/bin/wgsim_eval.pl
/usr/bin/zoom2sam.pl

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/samtools/LICENSE
/usr/share/package-licenses/samtools/htslib-1.9_LICENSE
/usr/share/package-licenses/samtools/lz4_LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/samtools.1
/usr/share/man/man1/wgsim.1
